// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Minimal stubs for compilation - proper generation requires protoc

package productv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

type ProductServiceClient interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductReply, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductReply, error)
	ActivateProduct(ctx context.Context, in *ActivateProductRequest, opts ...grpc.CallOption) (*ActivateProductReply, error)
	DeactivateProduct(ctx context.Context, in *DeactivateProductRequest, opts ...grpc.CallOption) (*DeactivateProductReply, error)
	ApplyDiscount(ctx context.Context, in *ApplyDiscountRequest, opts ...grpc.CallOption) (*ApplyDiscountReply, error)
	RemoveDiscount(ctx context.Context, in *RemoveDiscountRequest, opts ...grpc.CallOption) (*RemoveDiscountReply, error)
	ArchiveProduct(ctx context.Context, in *ArchiveProductRequest, opts ...grpc.CallOption) (*ArchiveProductReply, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductReply, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsReply, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductReply, error) {
	out := new(CreateProductReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/CreateProduct", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductReply, error) {
	out := new(UpdateProductReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/UpdateProduct", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *productServiceClient) ActivateProduct(ctx context.Context, in *ActivateProductRequest, opts ...grpc.CallOption) (*ActivateProductReply, error) {
	out := new(ActivateProductReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/ActivateProduct", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *productServiceClient) DeactivateProduct(ctx context.Context, in *DeactivateProductRequest, opts ...grpc.CallOption) (*DeactivateProductReply, error) {
	out := new(DeactivateProductReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/DeactivateProduct", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *productServiceClient) ApplyDiscount(ctx context.Context, in *ApplyDiscountRequest, opts ...grpc.CallOption) (*ApplyDiscountReply, error) {
	out := new(ApplyDiscountReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/ApplyDiscount", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *productServiceClient) RemoveDiscount(ctx context.Context, in *RemoveDiscountRequest, opts ...grpc.CallOption) (*RemoveDiscountReply, error) {
	out := new(RemoveDiscountReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/RemoveDiscount", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *productServiceClient) ArchiveProduct(ctx context.Context, in *ArchiveProductRequest, opts ...grpc.CallOption) (*ArchiveProductReply, error) {
	out := new(ArchiveProductReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/ArchiveProduct", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductReply, error) {
	out := new(GetProductReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/GetProduct", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *productServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsReply, error) {
	out := new(ListProductsReply)
	err := c.cc.Invoke(ctx, "/product.v1.ProductService/ListProducts", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

type ProductServiceServer interface {
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductReply, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductReply, error)
	ActivateProduct(context.Context, *ActivateProductRequest) (*ActivateProductReply, error)
	DeactivateProduct(context.Context, *DeactivateProductRequest) (*DeactivateProductReply, error)
	ApplyDiscount(context.Context, *ApplyDiscountRequest) (*ApplyDiscountReply, error)
	RemoveDiscount(context.Context, *RemoveDiscountRequest) (*RemoveDiscountReply, error)
	ArchiveProduct(context.Context, *ArchiveProductRequest) (*ArchiveProductReply, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error)
	mustEmbedUnimplementedProductServiceServer()
}

type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductServiceServer) ActivateProduct(context.Context, *ActivateProductRequest) (*ActivateProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateProduct not implemented")
}
func (UnimplementedProductServiceServer) DeactivateProduct(context.Context, *DeactivateProductRequest) (*DeactivateProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateProduct not implemented")
}
func (UnimplementedProductServiceServer) ApplyDiscount(context.Context, *ApplyDiscountRequest) (*ApplyDiscountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDiscount not implemented")
}
func (UnimplementedProductServiceServer) RemoveDiscount(context.Context, *RemoveDiscountRequest) (*RemoveDiscountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDiscount not implemented")
}
func (UnimplementedProductServiceServer) ArchiveProduct(context.Context, *ArchiveProductRequest) (*ArchiveProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// Minimal registration - actual registration requires proper descriptor
}
