// Code generated by protoc-gen-go. DO NOT EDIT.
// Minimal stubs for compilation - proper generation requires protoc

package productv1

// Message stubs

type Money struct {
	Numerator   int64 `json:"numerator,omitempty"`
	Denominator int64 `json:"denominator,omitempty"`
}

type Discount struct {
	Percent         int64 `json:"percent,omitempty"`
	StartDateSeconds int64 `json:"start_date_seconds,omitempty"`
	EndDateSeconds   int64 `json:"end_date_seconds,omitempty"`
}

type Product struct {
	ProductId        string     `json:"product_id,omitempty"`
	Name             string     `json:"name,omitempty"`
	Description      string     `json:"description,omitempty"`
	Category         string     `json:"category,omitempty"`
	BasePrice        *Money      `json:"base_price,omitempty"`
	EffectivePrice   *Money      `json:"effective_price,omitempty"`
	Discount         *Discount   `json:"discount,omitempty"`
	Status           string     `json:"status,omitempty"`
	CreatedAtSeconds int64       `json:"created_at_seconds,omitempty"`
	UpdatedAtSeconds int64       `json:"updated_at_seconds,omitempty"`
}

func (x *Product) GetBasePrice() *Money {
	if x != nil { return x.BasePrice }
	return nil
}

func (x *Product) GetEffectivePrice() *Money {
	if x != nil { return x.EffectivePrice }
	return nil
}

func (x *Product) GetDiscount() *Discount {
	if x != nil { return x.Discount }
	return nil
}

type CreateProductRequest struct {
	Name                 string `json:"name,omitempty"`
	Description          string `json:"description,omitempty"`
	Category             string `json:"category,omitempty"`
	BasePriceNumerator   int64  `json:"base_price_numerator,omitempty"`
	BasePriceDenominator int64  `json:"base_price_denominator,omitempty"`
}

type CreateProductReply struct {
	ProductId string `json:"product_id,omitempty"`
}

type UpdateProductRequest struct {
	ProductId   string `json:"product_id,omitempty"`
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Category    string `json:"category,omitempty"`
}

type UpdateProductReply struct{}

type ActivateProductRequest struct {
	ProductId string `json:"product_id,omitempty"`
}

type ActivateProductReply struct{}

type DeactivateProductRequest struct {
	ProductId string `json:"product_id,omitempty"`
}

type DeactivateProductReply struct{}

type ApplyDiscountRequest struct {
	ProductId         string `json:"product_id,omitempty"`
	DiscountPercent   int64  `json:"discount_percent,omitempty"`
	StartDateSeconds  int64  `json:"start_date_seconds,omitempty"`
	EndDateSeconds    int64  `json:"end_date_seconds,omitempty"`
}

type ApplyDiscountReply struct{}

type RemoveDiscountRequest struct {
	ProductId string `json:"product_id,omitempty"`
}

type RemoveDiscountReply struct{}

type ArchiveProductRequest struct {
	ProductId string `json:"product_id,omitempty"`
}

type ArchiveProductReply struct{}

type GetProductRequest struct {
	ProductId string `json:"product_id,omitempty"`
}

type GetProductReply struct {
	Product *Product `json:"product,omitempty"`
}

func (x *GetProductReply) GetProduct() *Product {
	if x != nil { return x.Product }
	return nil
}

type ListProductsRequest struct {
	Category  string `json:"category,omitempty"`
	PageSize  int32  `json:"page_size,omitempty"`
	PageToken string `json:"page_token,omitempty"`
}

type ListProductsReply struct {
	Products      []*Product `json:"products,omitempty"`
	NextPageToken string      `json:"next_page_token,omitempty"`
}

func (x *ListProductsReply) GetProducts() []*Product {
	if x != nil { return x.Products }
	return nil
}
